#!/usr/bin/env coffee

> fs > readdirSync
#   path > join
#   @3-/write
#
# ROOT = import.meta.dirname
# SRC = join ROOT,'src'
#
# file_li = readdirSync join(
#   ROOT,'src/watch'
# )
#
# cron_js = [
#   '''
# export default [
# '''
# ]
#
#
# gen = (name)=>
#   console.log name
#   cron_js.unshift "import * as #{name} from '../watch/#{name}.js'"
#   cron_js.unshift "import #{name}_conf from '../../conf/#{name}.js'"
#   cron_js.push "  ['#{name}',#{name}_conf,#{name}],"
#   return
#
# for i from file_li
#   if i.endsWith('.coffee')
#     name = i.slice(0,-7)
#     gen(name)
#
# save = (name, js_li)=>
#   write(
#     join(SRC,name+'.js')
#     '''// Don't edit ! generated by gen.coffee\n'''+js_li.join('\n')
#   )
#   return
#
# cron_js.push(']')
# save('gen/CRON', cron_js)
